const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';
const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

const FETCHING_GALLERY = 'FETCHING_GALLERY';
const FETCHED_GALLERY = 'FETCHED_GALLERY';

export default {
    FETCH_GALLERY_FAILURE,
    FETCH_GALLERY_SUCCESS,
    
    FETCHED_GALLERY,
    FETCHING_GALLERY
}