const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';
const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

const API_CALL_FETCHING_IMAGES = 'API_CALL_FETCHING_IMAGES';

const FETCH_EVENTS_BY_CATEGORY_SUCCESS = 'FETCH_EVENTS_BY_CATEGORY_SUCCESS';
const FETCH_EVENTS_BY_CATEGORY_FAILURE = 'FETCH_EVENTS_BY_CATEGORY_FAILURE'; 

const API_CALL_FETCHING_EVENTS = 'API_CALL_FETCHING_EVENTS';

export default {
    API_CALL_FETCHING_IMAGES,

    FETCH_GALLERY_FAILURE,
    FETCH_GALLERY_SUCCESS,
    
    API_CALL_FETCHING_EVENTS,

    FETCH_EVENTS_BY_CATEGORY_SUCCESS,
    FETCH_EVENTS_BY_CATEGORY_FAILURE
}