const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';
const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

const FETCHING_GALLERY = 'FETCHING_GALLERY';
const FETCHED_GALLERY = 'FETCHED_GALLERY';

const FETCH_EVENTS_BY_CATEGORY_SUCCESS = 'FETCH_EVENTS_BY_CATEGORY_SUCCESS';
const FETCH_EVENTS_BY_CATEGORY_FAILURE = 'FETCH_EVENTS_BY_CATEGORY_FAILURE'; 

export default {
    FETCH_GALLERY_FAILURE,
    FETCH_GALLERY_SUCCESS,
    
    FETCHED_GALLERY,
    FETCHING_GALLERY,

    FETCH_EVENTS_BY_CATEGORY_SUCCESS,
    FETCH_EVENTS_BY_CATEGORY_FAILURE
}